version: '3.8'

services:
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: treinamais_db
      POSTGRES_USER: treinamais_user
      POSTGRES_PASSWORD: treinamais_password
    ports:
      - "5433:5432"
    restart: unless-stopped

  web:
    build: .
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8001:8000"
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=treinamais.settings_docker
      - DATABASE_URL=postgres://treinamais_user:treinamais_password@db:5432/treinamais_db
      - SECRET_KEY=docker-dev-secret-key-change-in-production
    depends_on:
      - db
    restart: unless-stopped

volumes:
  postgres_data:
  static_volume:
  media_volume:
